### ISSUE TITLE
"systemctl reload naemon.service" doesn't do a "naemon-ctl configtest" beforehand

### ISSUE THREAD

**Issue by mennozon** [naemon/naemon#117]
The systemd unit file in Naemon 1.3.1 from the Debian 11 packages doesn't do a configtest when issuing a "systemctl reload naemon".

This causes the daemon to exit if the config contains errors.

I've applied the following workaround to the unit file, not sure if this is the preferred way to fix this.

```
--- a/lib/systemd/system/naemon.service	2022-04-27 11:14:13.000000000 +0200
+++ b/lib/systemd/system/naemon.service	2022-07-18 11:02:51.618608460 +0200
@@ -12,7 +12,7 @@
 ExecStartPre=/bin/chown -R naemon:naemon /run/naemon/
 ExecStartPre=/bin/su naemon --login --shell=/bin/sh "--command=/usr/bin/naemon --verify-config /etc/naemon/naemon.cfg"
 ExecStart=/usr/bin/naemon --daemon /etc/naemon/naemon.cfg
-ExecReload=/bin/kill -HUP $MAINPID
+ExecReload=/bin/su naemon --login --shell=/bin/sh "--command=/usr/bin/naemon --verify-config /etc/naemon/naemon.cfg" -- && /bin/kill -HUP $MAINPID
 User=naemon
 Group=naemon
 StandardOutput=journal
```

**Comment by jacobbaungard** [comment]
There's been quite a bit of discussion around this topic over here: https://github.com/naemon/naemon-core/pull/370

An approach have been agreed upon, but unfortunately it appears no one have had the time to implement and submit the change.

**Comment by mennozon** [comment]
I seem to have missed that pull request, my apologies.

I'll close the issue as it has been reported already.
