### ISSUE TITLE
@MAIL_PROG@ macro are not replaced with path to mail program during make

### ISSUE THREAD

**Issue by jryberg** [naemon/naemon#24]
E-mail notification are currently broken in our packages since the binary for @MAIL_PROG@ are not replaced during build to actual path to mail program.

The mail program should also be a dependency for the package

After installation of Naemon 0.8.0 the following file are affected: /etc/naemon/conf.d/commands.cfg

**Comment by starvingprogrammer** [comment]
I just had this issue in naemon 1.0.0-1.el6.x86_64, built from the dev instructions.  I did move my config over from a previous naemon install, so maybe some config setting got lost?
