### ISSUE TITLE
First login does not redirect

### ISSUE THREAD

**Issue by druchoo** [naemon/naemon#43]
RHEL 6.5 w/ packages from http://labs.consol.de/naemon/release/v1.0.0/rhel6/x86_64.

1. Clear cookies and/or cache? or use private mode
* navigate to http://{host}/naemon 
* get redirected http://{host}/naemon/cgi-bin/login.cgi?naemon
* enter credentials
* page stays on http://{host}/naemon/cgi-bin/login.cgi?naemon 
* manually navigate to http://{host}/naemon/ <- note trailing slash

Next time you authenticate @ http://{host}/naemon you are redirected correctly to http://{host}/naemon/#main.html. This seems to hold true for Chrome, Firefox, and Safari.

**Comment by sni** [comment]
Is this a new installation or an update?

**Comment by squareatom** [comment]
New. I've noticed the same behavior on previous release. Is this just me?

**Comment by sni** [comment]
probably not, i just thought this is fixed already, so i wanted to make sure its not a leftover from a previous installation. As a workaround, you should directly start with: http://{host}/naemon/
with the trailing slash.

**Comment by squareatom** [comment]
Your workaround does indeed work. Any idea if this is a quick coding fix or requires significant modifications on the backend?

**Comment by pshankland** [comment]
Can confirm this is still an issue on a clean CentOS 6.6 install following the following guide:

http://www.naemon.org/documentation/usersguide/quickstart-centos.html

If you go to http://<server>/naemon you get redirected to http://<server>/naemon/cgi-bin/login.cgi?naemon which then doesn't redirect after login. However, if you go to http://<server>/naemon/ you get redirected to http://<server>/naemon/cgi-bin/login.cgi?naemon/ which works fine.

**Comment by sni** [comment]
should be better with the next release. Meanwhile append the trailing slash manually.

**Comment by zzdga** [comment]
Hi,

quick fix is to set "Config Tool -> Thruk Settings -> start_page" to something like "/naemon/cgi-bin/tac.cgi"
worked for me.
