### ISSUE TITLE
naemon-livestatus crashes when running external command

### ISSUE THREAD

**Issue by scanbox** [naemon/naemon#45]
Hi!
I have compiled naemon core and livestatus from latest src from github. OS - FreeBSD 10.1. All work fine, but I have one problem - livestatus crashes when I run external command (Reschedule Next Check, Add Comment, Add Aknowledge, etc).
To exclude the possible influence of the Thruk issues, I tried to give the command directly to the socket:

echo "COMMAND [$(date +%s)] ADD_SVC_COMMENT;SW-566;IF_GI_5;1;scan;test" | ./naemon-unixcat /var/spool/naemon/rw/live

Livestatus (and the naemon process) was crashed. Livestatus log debug showed only the following:

2015-03-06 13:47:10 Starting 10 client threads
2015-03-06 13:47:10 Default stack size is 2097152
2015-03-06 13:47:10 Setting thread stack size to 2097152
2015-03-06 13:47:19 Accepted client connection on fd 22
2015-03-06 13:47:19 Query: COMMAND [1425638839] ADD_SVC_COMMENT;SW-566;IF_GI_5;1;scan;test

When I use external commands via named pipe file (native nagios method), Naemon work fine and don't crash.

**Comment by xoubih** [comment]
My analysis :
1) The NEB API doesnt' allow submitting commands, only getting events, so livestatus directly call nagios functions for submitting commands.
2) Nagios 4/Naemon have removed the  function submit_external_command() that was used by livestatus with nagios3 (cf api_incompat3to4.dox).
3) Livestatus use process_external_command1 instead (in answerCommandRequest (Store_1.cc:148))

But Nagios/Naemon is not multithreaded as Livestatus is and the mutex access control that was existing in the submit_external_command doesn't exist anymore so this is the origin of the crashes. Livestatus threads are directly accessing nagios data structures and when this is for writing, there's concurrency problems.

Nagios 3 : 
int submit_external_command(char *cmd, int *buffer_items) {
	int result = OK;
	if(cmd == NULL || external_command_buffer.buffer == NULL) {
		if(buffer_items != NULL)
			*buffer_items = -1;
		return ERROR;
		}
	/* obtain a lock for writing to the buffer */
	pthread_mutex_lock(&external_command_buffer.buffer_lock);
	if(external_command_buffer.items < external_command_buffer_slots) {


So anyway, i take a look how the native nagios nterface act for submitting commands :
It appear that the job is done by cmd.cgi, compiled from cmd.c, using the write_command_to_file (cmd.c :2224) function.
It doesn't explicitely use mutex, but it is still writting to the external command file and this is done using fprintf and the underlaying write command, wich is specified as atomic for write access on fifo :

Write requests of {PIPE_BUF} bytes or less shall not be interleaved with data from other processes doing writes on the same pipe. Writes of greater than {PIPE_BUF} bytes may have data interleaved, on arbitrary boundaries, with writes by other processes, whether or not the O_NONBLOCK flag of the file status flags is set.
(http://pubs.opengroup.org/onlinepubs/9699919799/)

I think livestatus should use the same trick and use the external command file to pass commands and get ride of this stability/concurrency problems with nagios4 and naemon.
Can anyone confirm the analysis and handle the correction ?

**Comment by sni** [comment]
Which version is that, we internally just send the command to the query handler since over two years: https://github.com/naemon/naemon-livestatus/blob/master/src/Store.cc#L149
See:
https://github.com/naemon/naemon-livestatus/commit/a72a5b59fe7ab1de5b9d18fc89489c6e0b27a5a4

**Comment by xoubih** [comment]
Whoops, i was on a mk-livestatus 1.2.4p15, sorry.
