### ISSUE TITLE
www-data no access to /var/lib/naemon/thruk

### ISSUE THREAD

**Issue by xlr-8** [naemon/naemon#46]
Hello,

I had a running setup with both naemon & thruk 0.8.0, but I decided to upgrade to 1.0.3.
After some issues, I decided to simply purge all the packages, and re-use my ansible playbooks to see.

The installation went fine, however thruk had some issue displaying the home page.
<pre>
root@monitoring:~# cat /etc/issue
Debian GNU/Linux 7 \n \l
root@monitoring:~# uname -a
Linux monitoring 2.6.32-042stab106.4 #1 SMP Fri Mar 27 15:19:28 MSK 2015 x86_64 GNU/Linux
root@monitoring:~# dpkg -l | grep -i naemon
ii  libnaemon                        1.0.3                         amd64        Library for Naemon - common data files
ii  naemon                           1.0.3                         amd64        A host/service/network monitoring and management system
ii  naemon-core                      1.0.3                         amd64        contains the Naemon core
ii  naemon-livestatus                1.0.3                         amd64        contains the Naemon livestatus eventbroker module
ii  naemon-thruk                     1.0.3                         amd64        This package contains the thruk gui for Naemon
ii  naemon-thruk-libs                1.0.3                         amd64        This package contains the thruk gui for Naemon
ii  naemon-thruk-reporting           1.0.3                         amd64        This package contains the reporting addon for naemons thruk gui useful for sla
</pre>

I saw an exception with permission denied in the thruk.log:
<pre>
[2015/04/25 15:41:58][monitoring][ERROR][Thruk.Controller.error] internal server error
[2015/04/25 15:41:58][monitoring][ERROR][Thruk.Controller.error] on page: http://xxx.xxx.xxx.xxx/thruk/cgi-bin/login.cgi?naemon/
[2015/04/25 15:45:26][monitoring][ERROR][Thruk.Controller.Root] Caught exception in Thruk::Controller::login->index "failed to create /var/lib/naemon/thruk/sessions: Permission denied at lib/Thruk/Utils/IO.pm line 55
	Thruk::Utils::IO::mkdir('/var/lib/naemon/thruk/sessions') called at /usr/share/naemon/script/../lib/Thruk/Controller/login.pm line 50
	Thruk::Controller::login::index('Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x5a34778)', 'Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	eval {...} called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	Catalyst::execute('Thruk=HASH(0x5c51760)', 'Thruk::Controller::login', 'Catalyst::Action=HASH(0x5a34778)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x5a34778)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 262
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x2530da8)', 'detach', 'Thruk=HASH(0x5c51760)', '/login/index') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 275
	Catalyst::Dispatcher::detach('Catalyst::Dispatcher=HASH(0x2530da8)', 'Thruk=HASH(0x5c51760)', '/login/index') called at /usr/lib/naemon/perl5/Catalyst.pm line 416
	Catalyst::detach('Thruk=HASH(0x5c51760)', '/login/index') called at /usr/share/naemon/script/../lib/Thruk/Controller/login.pm line 28
	Thruk::Controller::login::login_cgi('Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x5a34658)', 'Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	eval {...} called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	Catalyst::execute('Thruk=HASH(0x5c51760)', 'Thruk::Controller::login', 'Catalyst::Action=HASH(0x5a34658)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x5a34658)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Controller.pm line 161
	Catalyst::Controller::_ACTION('Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x5a2d490)', 'Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	eval {...} called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	Catalyst::execute('Thruk=HASH(0x5c51760)', 'Thruk::Controller::login', 'Catalyst::Action=HASH(0x5a2d490)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x5a2d490)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 262
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x2530da8)', 'forward', 'Thruk=HASH(0x5c51760)', '_ACTION') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 242
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x2530da8)', 'Thruk=HASH(0x5c51760)', '_ACTION') called at /usr/lib/naemon/perl5/Catalyst.pm line 401
	Catalyst::forward('Thruk=HASH(0x5c51760)', '_ACTION') called at /usr/lib/naemon/perl5/Catalyst/Controller.pm line 135
	Catalyst::Controller::_DISPATCH('Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 65
	Catalyst::Action::execute('Catalyst::Action=HASH(0x5a34b50)', 'Thruk::Controller::login=HASH(0x57e0568)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	eval {...} called at /usr/lib/naemon/perl5/Catalyst.pm line 1884
	Catalyst::execute('Thruk=HASH(0x5c51760)', 'Thruk::Controller::login', 'Catalyst::Action=HASH(0x5a34b50)') called at /usr/lib/naemon/perl5/Catalyst/Action.pm line 60
	Catalyst::Action::dispatch('Catalyst::Action=HASH(0x5a34b50)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 262
	Catalyst::Dispatcher::_do_forward('Catalyst::Dispatcher=HASH(0x2530da8)', 'forward', 'Thruk=HASH(0x5c51760)', '/login/_DISPATCH') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 242
	Catalyst::Dispatcher::forward('Catalyst::Dispatcher=HASH(0x2530da8)', 'Thruk=HASH(0x5c51760)', '/login/_DISPATCH') called at /usr/lib/naemon/perl5/Catalyst.pm line 401
	Catalyst::forward('Thruk=HASH(0x5c51760)', '/login/_DISPATCH') called at /usr/lib/naemon/perl5/Catalyst/Dispatcher.pm line 107
	Catalyst::Dispatcher::dispatch('Catalyst::Dispatcher=HASH(0x2530da8)', 'Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst.pm line 1830
	Catalyst::dispatch('Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 35
	Class::MOP::Method::Wrapped::__ANON__('Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 91
	Thruk::dispatch('Thruk=HASH(0x5c51760)') called at /usr/lib/naemon/perl5/Catalyst.pm line 2220
	Catalyst::try {...} () called at /usr/lib/naemon/perl5/Try/Tiny.pm line 81
	eval {...} called at /usr/lib/naemon/perl5/Try/Tiny.pm line 72
	Try::Tiny::try('CODE(0x5af1c80)', 'Try::Tiny::Catch=REF(0x5b3bca8)') called at /usr/lib/naemon/perl5/Catalyst.pm line 2229
	Catalyst::handle_request('Thruk', 'env', 'HASH(0x5bd0710)', 'response_cb', 'CODE(0x5bcbea8)') called at /usr/lib/naemon/perl5/Catalyst/Engine.pm line 805
	Catalyst::Engine::__ANON__('CODE(0x5bcbea8)') called at /usr/lib/naemon/perl5/Plack/Middleware/HTTPExceptions.pm line 32
	Plack::Middleware::HTTPExceptions::try {...} () called at /usr/lib/naemon/perl5/Try/Tiny.pm line 81
	eval {...} called at /usr/lib/naemon/perl5/Try/Tiny.pm line 72
	Try::Tiny::try('CODE(0x5b030c8)', 'Try::Tiny::Catch=REF(0x5b9fe68)') called at /usr/lib/naemon/perl5/Plack/Middleware/HTTPExceptions.pm line 41
	Plack::Middleware::HTTPExceptions::__ANON__('CODE(0x5b02d20)') called at /usr/lib/naemon/perl5/Plack/Util.pm line 301
	Plack::Util::__ANON__('CODE(0x5b0d468)') called at /usr/lib/naemon/perl5/Plack/Util.pm line 301
	Plack::Util::__ANON__('CODE(0x5b225e8)') called at /usr/lib/naemon/perl5/Plack/Util.pm line 301
	Plack::Util::__ANON__('CODE(0x5bcc748)') called at /usr/lib/naemon/perl5/Plack/Handler/FCGI.pm line 145
	Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x34608d0)', 'CODE(0x5ad27f0)', 'HASH(0x346caa0)') called at /usr/lib/naemon/perl5/Catalyst/Engine.pm line 787
	Catalyst::Engine::run('Catalyst::Engine=HASH(0x37118f0)', 'Thruk', 'CODE(0x5ad27f0)', undef, 'HASH(0x346caa0)', 'Plack::Handler::FCGI=HASH(0x34608d0)') called at /usr/lib/naemon/perl5/Catalyst.pm line 2701
	Catalyst::run('Thruk', undef, 'HASH(0x346caa0)', 'Plack::Handler::FCGI=HASH(0x34608d0)') called at /usr/lib/naemon/perl5/Catalyst/ScriptRole.pm line 99
	Catalyst::ScriptRole::_run_application('Catalyst::Script::FastCGI=HASH(0x1eda150)') called at /usr/lib/naemon/perl5/Catalyst/ScriptRole.pm line 69
	Catalyst::ScriptRole::run('Catalyst::Script::FastCGI=HASH(0x1eda150)') called at /usr/lib/naemon/perl5/Catalyst/ScriptRunner.pm line 50
	Catalyst::ScriptRunner::run('Catalyst::ScriptRunner', 'Thruk', 'FastCGI') called at /usr/share/naemon/script/thruk_fastcgi.pl line 28"
[2015/04/25 15:45:26][monitoring][ERROR][Thruk.Controller.error] internal server error
[2015/04/25 15:45:26][monitoring][ERROR][Thruk.Controller.error] on page: http://xxx.xxx.xxx.xxx/thruk/cgi-bin/login.cgi?naemon/
</pre>
I checked the user/group and both naemon/www-data are belonging to each-others groups.

To solve the issue, I finally have to give writing rights to the group naemon (to which www-data belongs):
<pre>
root@monitoring:~# ls -l /var/lib/naemon/
total 168
[...]
drwxr-xr-x 2 naemon naemon  4096 Apr 25 15:38 thruk
root@monitoring:~# chmod 775 /var/lib/naemon/thruk/
</pre>

Everything worked fine afterwards. I checked the other issues, but didn't find something similar, if the case is already solve, then forget about it.

Regards,

**Comment by sni** [comment]
Could you double check your ansible playbooks and make sure that the www-data user has the group naemon.
We set that in https://github.com/naemon/naemon/blob/master/debian/naemon-thruk.postinst#L51
but puppet, ansible, chef etc... tend to break such things.

**Comment by xlr-8** [comment]
Hi @sni,

Sorry for the delay in response. I did check after passing ansible on the server.

The problem wasn't about the user/group but about the fact that www-data needed writing permission. Which is set here: https://github.com/naemon/naemon/blob/master/debian/naemon-thruk.postinst#L27

Therefore I double check and I was indeed changing the group of the directory, sorry for the noise.

Thank for the hand!
