### ISSUE TITLE
result of global commands like diabled notifications not shown

### ISSUE THREAD

**Issue by tsoehl** [naemon/naemon#48]
Hi.

When i set global commands by the Tactical Overview like diable notifications, i didnt see the result "red disabled". But when i opend the page "configuration" and then go back to Tactical Overvie i see that the notifications are disabled.

Version Naemon 1.0.3,Thruk 1.88-2

**Comment by sni** [comment]
I'd say this is fixed already in 2.0. Please reopen if this issue still persists in the latest release.
