### ISSUE TITLE
thruk, no paging at section configuration

### ISSUE THREAD

**Issue by tsoehl** [naemon/naemon#49]
Hi

When i go to the site configuration i only the the result 100 of 100 and there is no paging option.
When i insert a * at the thruk setting at 100 in the section paging_steps nothing changed. I had to set the * for all, than i have the paging drop down.

Version Naemon 1.0.3,Thruk 1.88-2

**Comment by sni** [comment]
You could try again with the latest release. Afaik this is fixed already.
