### ISSUE TITLE
Thruk Addons & Plugin Manager config file not writable !

### ISSUE THREAD

**Issue by mgadi** [naemon/naemon#50]
Hy everyone !
I've installed Naemon 1.0.3 with https://github.com/mgadi/naemonbox/releases/download/0.0.7-RC3/naemonbox-0.0.7-RC3.tar.gz
* I don't know wich file to look at it, to find an issue. Could you please help me ?

**Comment by sni** [comment]
You should install Naemon and Thruk via the labs repository from here: https://labs.consol.de/repo/stable/ Then it should just work.

**Comment by mgadi** [comment]
I'm sorry, this is not the place to talk about my  project NaemonBox, but in fact the installation of all the components I need, to make a good monitoring platform gathered in naemonbox (from the link I sent just before) . To install naemon , I use the debian packages from this site (because we have a proxy in my company) :
https://labs.consol.de/naemon/release/v1.0.3/debian7/amd64/

The script inside the tar.gz do the install  like this :
* dpkg -i libnaemon_1.0.3_debian8_amd64.deb
* dpkg -i naemon/naemon*.deb

So, could you please help me ?

ps: I will be delighted to meet you because I think you are doing a good job ...

**Comment by mgadi** [comment]
it appears the same error on http://demo.thruk.org/

![plugin-manager-config-file-not-writable](https://cloud.githubusercontent.com/assets/4088423/9739270/3e174254-564f-11e5-90b4-8411e69bcb7b.PNG)

**Comment by sni** [comment]
On demo.thruk.org its intentional. 
The Plugin Manager needs write permissions on /etc/thruk/plugins-enabled/
On older naemon installations, it may be /etc/naemon/plugins-enabled but this will be moved to the former one.

**Comment by mgadi** [comment]
Thanks for your answer.

**Comment by nickjwest** [comment]
I have the same issue when trying to use the Config Tool to change passwords. I have made the /etc/thruk/plugins/plugins-enabled directory 777 but its still not fixed.
