### ISSUE TITLE
naemon-thruk depends on thruk?

### ISSUE THREAD

**Issue by zoredache** [naemon/naemon#55]
I also took a look at using the 1.0.4 preview of the Debian packages.  But these packages do
not seem to be installable. The `naemon-thruk` package depends on a package `thruk`, but that isn't available at the preview/1.0.4 url, in the Debian 8 official repos, or anywhere else.  Where should the
`thruk` package be coming from?  Or is that in invalid dependency?

Ref:

- https://labs.consol.de/naemon/preview/v1.0.4/debian8/amd64/
- https://github.com/naemon/naemon/blob/master/debian/control#L80

**Comment by sni** [comment]
All packages end up in this repository: https://labs.consol.de/repo/stable/
Thats also the source for the Thruk packages. If it helps, we could put the thruk packages into the naemon folder as well for people who don't want to add a repository but to download the files manually. But you won't get updates that way.
