### ISSUE TITLE
rpm based distro: rpmbuild -tb naemon-1.0.4.tar.gz fails if httpd package is not installed

### ISSUE THREAD

**Issue by olahaye74** [naemon/naemon#57]
Hi,

Small but annoying build problem regarding naemon-1.0.4.
If the httpd package is not installed (/etc/httpd path missing) then the install section is thruk Makefile will install naemon.conf in /etc/apache2/conf.dnaemon.conf instead of /etc/httpd/conf.d/naemon.conf
this results in an inconsistent path for the naemon.conf file in the %file section. The spec file tries to find the naemon.conf file in /etc/httpd/conf.d (correct) while it is wrongly installed in a debian style path /etc/apache2/conf.d/ (wrong).

SOLUTIONS (choose one):
1/ add httpd in build deps (easy but ugly) => the Make install will find /etc/httpd and choose correct location.
2/ do not default to debian apache config path on rpm distro. => in none of the apache config path is detected then default to /etc/apache2/... on a deb system and /etc/httpd/... on a rpm system.

**Comment by sni** [comment]
It's not only debian style, but suse sles uses /etc/apache2 as well. Debian does not use RPMs, so thats irrelevant. So we could use the sles_version macro and choose the path from that.

**Comment by olahaye74** [comment]
Sorry, I forgot SuSE.. Anyway, I know that debian doesn't uses rpm, but I was saying that the thruk Makefile install: section was defaulting to a wrong path when trying to install naemon.cf file on a CentOS/RHEL or Fedora distro without httpd package installed (/etc/httpd path not present).

So, in the thruk Makefile, a better distro detection should be put in place when trying to install naemon.cfg (thruk Makefile, install: section) (/etc/httpd on RHEL/CentOS/Fedora and /etc/apache2 on SuSE/debian/...)
Then in the spec file, a macro should be used so the %file section tries to find the naemon.conf file in /etc/httpd/conf.d on CentOS/RHEL/Fedora and in /etc/apache2/conf.d on SuSE)

**Comment by sni** [comment]
Should be fixed meanwhile in thruk. Closing it here since naemon is not related to httpd in any way.
