### ISSUE TITLE
Naemon service crashes after x amount off time

### ISSUE THREAD

**Issue by OBenned** [naemon/naemon#58]
Hi.

I have some issues with naemon atm.
On both version 1.0.3 and 1.0.4 the Naemon service crashes after some time (runs fine until then)
When i try and start i again it says: 
runuser: cannot set user id: Resource temporarily unavailable
Cowardly refusing to start, failed to verify config
Run '/etc/rc.d/init.d/naemon configtest' for more info

The only way to start Naemon again, as far as i can tell, is to reboot the server

Naemon is running on Centos 6.8

**Comment by sni** [comment]
Can you retry with the 1.0.5?

**Comment by tristangallet** [comment]
Hello, in Debian, the stable repository is not in 1.05, could you update it ?

**Comment by sni** [comment]
please try again

**Comment by tristangallet** [comment]
Perfect, thanks a lot !
Version table:
 *** 1.0.5 0
        500 http://labs.consol.de/repo/stable/debian/ jessie/main amd64 Packages
