### ISSUE TITLE
Naemon crashing

### ISSUE THREAD

**Issue by viktorgunnarson** [naemon/naemon#59]
We had some difficulties upgrading Naemon to 1.04 so we ended up with a clean install, but now Naemon has started crashing sporadically. The Naemon service simply dies and after a manual restart of the service everything works fine for some time.

The following error is presented in Thruk:
> Naemon: ERROR: failed to open socket /var/cache/naemon/live: No such file or directory (/var/cache/naemon/live)

I found the following in /var/log/naemon/naemon.log:

> [1465522622] Error: Polling for input on 0xb94130 failed: Interrupted system call
> [1465522622] Event broker module 'NERD' deinitialized successfully.
> [1465522622] livestatus: deinitializing
> [1465522622] Event broker module '/usr/lib64/naemon/naemon-livestatus/livestatus.so' deinitialized successfully.

As far as I know we have not changed anything else than moving to 1.04. This is running on a RHEL 6 machine.

**Comment by tristangallet** [comment]
Hello, i've got the same on Debian 8X64 with last patches.
Tested on a fresh install and after upgraded from naemon 1.03
Installed with apt and the official repository.

**Comment by sni** [comment]
This should be fixed with the 1.0.5 now. Thanks for reporting this.
