### ISSUE TITLE
Naemon "devel"?

### ISSUE THREAD

**Issue by SeLLeRoNe** [naemon/naemon#64]
Hi there,

i'm trying to install latest Merlin, but durng the command autogen.sh (which actually call the ./configure) i receive this error:
./configure: line 12732: syntax error near unexpected token `naemon,'
./configure: line 12732: `PKG_CHECK_MODULES(naemon, naemon >= 0.8)'

I've installed Naemon from source, and that part is working fine, the only thing is that Merlin is unable to find it (more likely the path /usr/local/naemon/lib/pkgconfig/naemon.pc), i've tryed to add this path to PKG_CONFIG_PATH variable but is pointless, i'm quite sure that on CentOS that variable is not even used (it is actually empty before i set it).

So, my OS is CentOS 7, and i would like to know if there is something more specific to add Naemon debug (like in nagios was make install-debug).

Thanks

Best regards

**Comment by sni** [comment]
When using Centos, just use the Labs repository: https://labs.consol.de/repo/stable/#_7
and install the naemon-devel package. The general advice is do not use source installation unless you really need to.

**Comment by SeLLeRoNe** [comment]
I would agree with you at some point to use repositories, but i prefer compile software from source, always did this way for long time now :)

Anyway, thanks for pointing to that repository, i already had that.. i just wanted to know if there was a way from source to do so.

Thanks

**Comment by SeLLeRoNe** [comment]
Also using neamon-devel from the repository actually merlin is replying with the same error.

I'm gonna try to ask on merlin project

**Comment by SeLLeRoNe** [comment]
UPDATE:
The problem is apparently related to automake 1.15 which the merlin configure is not working well with.

Sayd that, i still think would be nice have during make install (or on a separate make install-devel) that naemon.pc file is copied into the appropriate folder (like /usr/lib/pkgconfig or /usr/lib64/pkgconfig/ depending on the OS Architecture) beside the standard NAEMON-PATH/lib/pkgconfig/

Best regards
