### ISSUE TITLE
Lost all configuration in thruk  after upgrading from 1.05 to 1.06 on Debian

### ISSUE THREAD

**Issue by tristangallet** [naemon/naemon#66]
Hello, from Naemon 1.05 on Debian 8 X64, installed with offcial repository, all my configuration is lost in thruk with the update.

Can't connect to Thruk, except with naemon / naemon (i had 2 users before) and  no host in thruk. 

Seems that naemon is ok, i can see the logs with the checks. Any Idea ?

Thanks,
Regards,
Tristan

**Comment by sni** [comment]
which config did you exactly loose?

**Comment by tristangallet** [comment]
Seems that it is only thruk, my files in /etc/naemon are ok, i can see that naemon is doing checks with the logs, but thruks seems to be not connected : i've lost my 2 users, password is reset an user naemon which was deleted is present.

**Comment by sni** [comment]
If you have updated from 1.0.4 or older, then the Naemon specific Thruk has been replace with the standard Thruk which also implies that the Thruk config files moved from /etc/naemon to /etc/thruk. However, the thruk config should have been migrated to /etc/thruk/thruk_local.d. Maybe it didn't work for the htpasswd.

**Comment by tristangallet** [comment]
Hum, for the htpasswd, there is in version 1.05 : one in /etc/naemon and i've got mine in /etc/thruk/htpasswd, i will test after upgrade if it's ok. But the htpasswd is nothing, i've no host in the thruk interface...

**Comment by sni** [comment]
The cgi.cfg has moved as well to /etc/thruk. Could you check that one? It contains authorization information.

**Comment by tristangallet** [comment]
ok, so in version 1.05, i've already have a /etc/thruk and /etc/thruk/htpasswd with my users and already have a modified /etc/thruk/cgi.conf. After upgrading via apt-get and your repository, /etc/thruk/htpasswd was replaced with old /etc/naemon/htpasswd and /etc/thruk/cgi.conf replaced with the version of the package !

I've copied from my backup in 1.05 these two files and everything is ok ! Maybe a problem in the update script ? Anyway, thanks for your help, it's ok for me now.

**Comment by sni** [comment]
Seems like it tried to migrate thinks twice then. Thanks for reporting this.

**Comment by sni** [comment]
I just double checked the debian scripts: https://github.com/naemon/naemon/blob/master/debian/naemon-thruk.postinst#L28
The files should be moved after the first update.

**Comment by sni** [comment]
closing this since the migration is a one time thing, should not occur again.
