### ISSUE TITLE
Error after update Naemon and Thruk

### ISSUE THREAD

**Issue by pantinanco** [naemon/naemon#68]
Hello,
I like to greet you, I write to you since I need your help. I recently did the update of our monitoring platform Naemon, which was done without problems. But when I enter the portal and see the states of the hosts, it shows me the following error:

"No Backend available
None of the backends could be reached, please have a look at the logfile for detailed information and make sure the core is up and running.

Details:
Naemon: ERROR: failed to open socket / var / cache / naemon / live: No such file or directory .. (/ var / cache / naemon / live) "

I have reviewed the error logs but I could not find the solution. As a result, if I check the configuration of objects through the web, it shows me the data of the hosts, such as IP, hostname and the hostgroup to which it belongs.

Information delivered by the systemctl status naemon.service:

"● naemon.service - Naemon Monitoring Daemon
   Loaded: loaded (/usr/lib/systemd/system/naemon.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-05-11 10:00:06 CLT; 1h 2min ago
     Docs: http://naemon.org/documentation
  Process: 20853 ExecStart = / usr / bin / naemon --daemon /etc/naemon/naemon.cfg (code = exited, status = 1 / FAILURE)
  Process: 20850 ExecStartPre = / usr / bin / chown -R naemon / var / run / naemon / (code = exited, status = 0 / SUCCESS)
  Process: 20846 ExecStartPre = / usr / bin / mkdir / var / run / naemon (code = exited, status = 1 / FAILURE)

May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: Starting Naemon Monitoring Daemon ...
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: naemon.service: control process exited, ... = 1
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: Failed to start Naemon Monitoring Daemon.
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: Unit naemon.service entered failed state.
May 11 10:00:06 naemon-sion-alicopsa-local systemd [1]: naemon.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[Root @ naemon-sion-alicopsa-local ~] # service naemon restart
Redirecting to / bin / systemctl restart naemon.service
Job for naemon.service failed because the control process exited with error code. See "systemctl status naemon.service" and "journalctl -xe" for details.
[Root @ naemon-sion-alicopsa-local ~] # systemctl status naemon.service
● naemon.service - Naemon Monitoring Daemon
   Loaded: loaded (/usr/lib/systemd/system/naemon.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-05-11 11:15:12 CLT; 15s ago
     Docs: http://naemon.org/documentation
  Process: 22092 ExecStart = / usr / bin / naemon --daemon /etc/naemon/naemon.cfg (code = exited, status = 1 / FAILURE)
  Process: 22088 ExecStartPre = / usr / bin / chown -R naemon / var / run / naemon / (code = exited, status = 0 / SUCCESS)
  Process: 22083 ExecStartPre = / usr / bin / mkdir / var / run / naemon (code = exited, status = 1 / FAILURE)

May 11 11:15:12 naemon-sion-alicopsa-local systemd [1]: Starting Naemon Monitoring Daemon ...
May 11 11:15:12 pm naemon-sion-alicopsa-local systemd [1]: naemon.service: control process exited, ... = 1
May 11 11:15:12 pm naemon-sion-alicopsa-local systemd [1]: Failed to start Naemon Monitoring Daemon.
May 11 11:15:12 AM naemon-sion-alicopsa-local systemd [1]: Unit naemon.service entered failed state.
May 11 11:15:12 pm naemon-sion-alicopsa-local systemd [1]: naemon.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
"

Waiting for your help and prompt reply, I say goodbye.

Thanks in advance.

Best regards.

Pablo Antiñanco Soto

**Comment by sni** [comment]
Is naemon-livestatus installed and enabled?

**Comment by pantinanco** [comment]
Hi, I think that since the platform was working correctly, after the version update started the problems...

**Comment by tvestelind** [comment]
Do you have the directory `/var/cache/naemon/`? If yes, what are the permissions? If no, try creating it and restart naemon.

**Comment by tvestelind** [comment]
Also, check the log file defined by `log_file=` in `/etc/naemon/naemon.cfg` and see if you can see any obvious errors.

**Comment by pantinanco** [comment]
Yes, the directory /var/cache/naemon/ already exists and its permissions are 775 (Owner (rwx),group(rwx),other (rx))

The log file show me the following error:

[1494512112] Error in configuration file '/etc/naemon/naemon.cfg' - Line 344 (Warning: Failed to open check_result_path '/var/cache/naemon/checkresults': No such file or directory)

I create the path but still not working.

**Comment by sni** [comment]
maybe it is an permission issue. You could try to reinstall naemon. This should create all required folders.
