### ISSUE TITLE
passive service checks would return "Service check timed out after 0.00 seconds"

### ISSUE THREAD

**Issue by mahsanaru** [naemon/naemon#70]
I'm trying to use naemon with nrdp for distributed monitoring but the passive checks on my central naemon return "Service check timed out after 0.00 seconds"
**naemon log**
[1496057148] PASSIVE SERVICE CHECK: controller;Uptime;2;(Service check timed out after 0.00 seconds)

I have seen this as a bug in nagios and it seems it has already been fixed in the newer version. is there a workaround for this?

Thanks in advance.

Best regards.

**Comment by micoots** [comment]
Hi. Did you ever find a solution to this?

I've just installed a naemon server, then applied nrdp to it, then used ncpa to report it's checks to nrdp into naemon, and get exactly the error you are seeing.

I've verified via debug mode on ncpa client that checks are successful and sent to nrdp successfully.

Been on this problem for an hour can't figure out what's happening.

**Comment by sni** [comment]
Right, this seems to be a bug in nrdp then.
