### ISSUE TITLE
Non-English characters are not shown

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [naemon/naemon#93]
I was using before OMD 1.10 + Thruk + Shinken.
Now I'm using OMD 2.90 labs + Thruk + Naemon.

It works well, but all non-English characters are shown as **?**.
With Shinken (Python based) I didn't experience this problem.
The configuration is the same for both of them.

**Comment by sni** [comment]
could you try the latest omd-labs nightly. there were some issues which have been fixed meanwhile.

**Comment by DavidPerezIngeniero** [comment]
Thanks for your quick response.
I remember I can have 2 versions of OMD simultaneously installed.

**Comment by sni** [comment]
> I remember I can have 2 versions of OMD simultaneously installed.

yes, thats right.
