### ISSUE TITLE
Naemon fails to install on ubuntu 18.04 via opensuse repos.

### ISSUE THREAD

**Issue by burnsjake** [naemon/naemon#99]
If installing the latest naemon on ubuntu 18.04 using the opensuse repos, the installation process fails saying:
```
Errors were encountered while processing:
 thruk-base
 thruk
 thruk-plugin-reporting
 naemon-thruk
 naemon
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

If installed via the labs.consol.de repos, the installation completes without error.

**Comment by sni** [comment]
something with the postinst script goes wrong:

```
To activate the new configuration, you need to run:
  service apache2 restart
ERROR: Conf thruk does not exist!
dpkg: error processing package thruk-base (--configure):
 installed thruk-base package post-installation script subprocess returned error exit status 1
```

**Comment by sni** [comment]
this has been fixed in https://github.com/sni/Thruk/commit/654fed10ad1a08bdac9c6c99bc17bb52e9020937
But it seems like there hasn't been any new packages on OBS since then. At least for Ubuntu 18.04 because it missed some dependecies.
